version: '3.8'
name: etik

services:
  etik-api:
    image: etik/etik-fe
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - etik-network

networks:
  etik-network:
    external: true
